# Generated by Django 4.2.7 on 2023-12-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indumentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='titulo')),
                ('description', models.TextField(verbose_name='descripción')),
                ('image', models.ImageField(upload_to='project', verbose_name='imagen')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
            ],
            options={
                'verbose_name': 'indumentaria',
                'verbose_name_plural': 'indumentarias',
                'ordering': ['-created'],
            },
        ),
    ]
