# Generated by Django 5.0 on 2023-12-12 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Indumentaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indumentaria',
            options={'ordering': ['created'], 'verbose_name': 'indumentaria', 'verbose_name_plural': 'indumentarias'},
        ),
    ]
