# Generated by Django 4.2.7 on 2023-12-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Indumentaria', '0003_indumentaria_historico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indumentaria',
            options={},
        ),
    ]
