# Generated by Django 4.2.7 on 2023-12-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=20, verbose_name='apellido')),
                ('nombre', models.TextField(verbose_name='nombre')),
                ('image', models.ImageField(upload_to='project', verbose_name='imagen')),
                ('descripcion', models.TextField(verbose_name='descripcion')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
            ],
            options={
                'verbose_name': 'integrante',
                'verbose_name_plural': 'integrantes',
                'ordering': ['-created'],
            },
        ),
    ]
