# Generated by Django 4.2.7 on 2023-12-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name='nombre'),
        ),
    ]
