# Generated by Django 4.2.7 on 2023-12-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_about_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.CharField(default='xxxxx@xxxxxxxx.com', max_length=100, verbose_name='email'),
        ),
    ]
